customhost = "employee1.cadbupwobwlq.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee1"
custombucket = "chuazisan-employee"
customregion = "us-east-1"
